/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author joshu
 */
public class RecepcionArticulos extends javax.swing.JFrame {

    /**
     * Creates new form RecepcionArticulos
     */
    public RecepcionArticulos() {
        initComponents();
        //paquete
        label_paquete_1.setVisible(false);
        label_paquete_2.setVisible(false);
        label_paquete_3.setVisible(false);
        txt_paquete_Tipoentrega.setVisible(false);
        txt_paquete_electronico.setVisible(false);
        txt_paquete_fragil.setVisible(false);
        
        //sobre
        label_sobre_1.setVisible(false);
        label_sobre_2.setVisible(false);
        txt_contenido_sobre.setVisible(false);
        txt_tiposobre.setVisible(false);
        
        //revista
        label_revista_1.setVisible(false);
        label_revista_2.setVisible(false);
        label_revista_3.setVisible(false);
        txt_revista_catalogo.setVisible(false);
        txt_revista_nombre.setVisible(false);
        txt_revista_tema.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        txt_revista_catalogo = new javax.swing.JComboBox<>();
        label_revista_3 = new javax.swing.JLabel();
        txt_revista_tema = new javax.swing.JComboBox<>();
        label_revista_2 = new javax.swing.JLabel();
        txt_revista_nombre = new javax.swing.JTextField();
        label_revista_1 = new javax.swing.JLabel();
        label_paquete_1 = new javax.swing.JLabel();
        txt_paquete_electronico = new javax.swing.JComboBox<>();
        label_paquete_3 = new javax.swing.JLabel();
        txt_paquete_Tipoentrega = new javax.swing.JComboBox<>();
        label_paquete_2 = new javax.swing.JLabel();
        txt_paquete_fragil = new javax.swing.JComboBox<>();
        txt_contenido_sobre = new javax.swing.JTextField();
        txt_fecharetiro = new com.toedter.calendar.JDateChooser();
        label_sobre_2 = new javax.swing.JLabel();
        txt_idremitente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_peso = new javax.swing.JTextField();
        txt_costo = new javax.swing.JTextField();
        label_sobre_1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_des = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_tiposobre = new javax.swing.JComboBox<>();
        txt_tipoarticulo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FondoArticulos = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reload (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 30, -1));

        txt_revista_catalogo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        txt_revista_catalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_revista_catalogoMouseClicked(evt);
            }
        });
        getContentPane().add(txt_revista_catalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 50, -1));

        label_revista_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_revista_3.setForeground(new java.awt.Color(255, 255, 255));
        label_revista_3.setText("Catalogo");
        getContentPane().add(label_revista_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        txt_revista_tema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negocios", "Medicina", "Cocina", "Moda", "Tecnología", "Otros" }));
        txt_revista_tema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_revista_temaMouseClicked(evt);
            }
        });
        getContentPane().add(txt_revista_tema, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 120, -1));

        label_revista_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_revista_2.setForeground(new java.awt.Color(255, 255, 255));
        label_revista_2.setText("Nombre");
        getContentPane().add(label_revista_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        txt_revista_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_revista_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 110, -1));

        label_revista_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_revista_1.setForeground(new java.awt.Color(255, 255, 255));
        label_revista_1.setText("Nombre");
        getContentPane().add(label_revista_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        label_paquete_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_paquete_1.setForeground(new java.awt.Color(255, 255, 255));
        label_paquete_1.setText("Fragil");
        getContentPane().add(label_paquete_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        txt_paquete_electronico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        getContentPane().add(txt_paquete_electronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 50, -1));

        label_paquete_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_paquete_3.setForeground(new java.awt.Color(255, 255, 255));
        label_paquete_3.setText("Electronico");
        getContentPane().add(label_paquete_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        txt_paquete_Tipoentrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bolsa", "Caja" }));
        getContentPane().add(txt_paquete_Tipoentrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 120, -1));

        label_paquete_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_paquete_2.setForeground(new java.awt.Color(255, 255, 255));
        label_paquete_2.setText("Entrega");
        getContentPane().add(label_paquete_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        txt_paquete_fragil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        getContentPane().add(txt_paquete_fragil, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 50, -1));

        txt_contenido_sobre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_contenido_sobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 140, -1));

        txt_fecharetiro.setBackground(new java.awt.Color(0, 102, 153));
        txt_fecharetiro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_fecharetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 140, 20));

        label_sobre_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_sobre_2.setForeground(new java.awt.Color(255, 255, 255));
        label_sobre_2.setText("Contenido");
        getContentPane().add(label_sobre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        txt_idremitente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_idremitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Costo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        txt_peso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 140, -1));

        txt_costo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 140, -1));

        label_sobre_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_sobre_1.setForeground(new java.awt.Color(255, 255, 255));
        label_sobre_1.setText("Tipo de sobre");
        getContentPane().add(label_sobre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        txt_des.setColumns(20);
        txt_des.setRows(3);
        jScrollPane1.setViewportView(txt_des);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 280, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de articulo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        registrar.setBackground(new java.awt.Color(0, 102, 153));
        registrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registrar.setText("Agregar articulo");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de retiro");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Peso");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txt_tiposobre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aereo", "Manila" }));
        getContentPane().add(txt_tiposobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 140, -1));

        txt_tipoarticulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sobre", "Paquete", "Revista" }));
        txt_tipoarticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_tipoarticuloMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_tipoarticuloMousePressed(evt);
            }
        });
        getContentPane().add(txt_tipoarticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descripción");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Remitente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        FondoArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoCounter.jpg"))); // NOI18N
        getContentPane().add(FondoArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 420));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setText("jTextField1");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tipoarticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tipoarticuloMouseClicked
        
        
        
    }//GEN-LAST:event_txt_tipoarticuloMouseClicked

    private void txt_revista_temaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_revista_temaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_revista_temaMouseClicked

    private void txt_revista_catalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_revista_catalogoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_revista_catalogoMouseClicked

    private void txt_tipoarticuloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tipoarticuloMousePressed
        
    }//GEN-LAST:event_txt_tipoarticuloMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(txt_tipoarticulo.getSelectedItem().toString().equalsIgnoreCase("Sobre")){
            //paquete
            label_paquete_1.setVisible(false);
            label_paquete_2.setVisible(false);
            label_paquete_3.setVisible(false);
            txt_paquete_Tipoentrega.setVisible(false);
            txt_paquete_electronico.setVisible(false);
            txt_paquete_fragil.setVisible(false);
        
            //sobre
            label_sobre_1.setVisible(true);
            label_sobre_2.setVisible(true);
            txt_contenido_sobre.setVisible(true);
            txt_tiposobre.setVisible(true);
            
            //revista
            label_revista_1.setVisible(false);
            label_revista_2.setVisible(false);
            label_revista_3.setVisible(false);
            txt_revista_catalogo.setVisible(false);
            txt_revista_nombre.setVisible(false);
            txt_revista_tema.setVisible(false);
        }
        
        if(txt_tipoarticulo.getSelectedItem().toString().equalsIgnoreCase("Paquete")){
            //paquete
            label_paquete_1.setVisible(true);
            label_paquete_2.setVisible(true);
            label_paquete_3.setVisible(true);
            txt_paquete_Tipoentrega.setVisible(true);
            txt_paquete_electronico.setVisible(true);
            txt_paquete_fragil.setVisible(true);
        
            //sobre
            label_sobre_1.setVisible(false);
            label_sobre_2.setVisible(false);
            txt_contenido_sobre.setVisible(false);
            txt_tiposobre.setVisible(false);
            
            //revista
            label_revista_1.setVisible(false);
            label_revista_2.setVisible(false);
            label_revista_3.setVisible(false);
            txt_revista_catalogo.setVisible(false);
            txt_revista_nombre.setVisible(false);
            txt_revista_tema.setVisible(false);
        }
        
        if(txt_tipoarticulo.getSelectedItem().toString().equalsIgnoreCase("Revista")){
            //paquete
            label_paquete_1.setVisible(false);
            label_paquete_2.setVisible(false);
            label_paquete_3.setVisible(false);
            txt_paquete_Tipoentrega.setVisible(false);
            txt_paquete_electronico.setVisible(false);
            txt_paquete_fragil.setVisible(false);
        
            //sobre
            label_sobre_1.setVisible(false);
            label_sobre_2.setVisible(false);
            txt_contenido_sobre.setVisible(false);
            txt_tiposobre.setVisible(false);
            
            //revista
            label_revista_1.setVisible(true);
            label_revista_2.setVisible(true);
            label_revista_3.setVisible(true);
            txt_revista_catalogo.setVisible(true);
            txt_revista_nombre.setVisible(true);
            txt_revista_tema.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
       
    }//GEN-LAST:event_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecepcionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecepcionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecepcionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecepcionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecepcionArticulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoArticulos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextField3;
    private javax.swing.JLabel label_paquete_1;
    private javax.swing.JLabel label_paquete_2;
    private javax.swing.JLabel label_paquete_3;
    private javax.swing.JLabel label_revista_1;
    private javax.swing.JLabel label_revista_2;
    private javax.swing.JLabel label_revista_3;
    private javax.swing.JLabel label_sobre_1;
    private javax.swing.JLabel label_sobre_2;
    public javax.swing.JButton registrar;
    public javax.swing.JTextField txt_contenido_sobre;
    public javax.swing.JTextField txt_costo;
    public javax.swing.JTextArea txt_des;
    public com.toedter.calendar.JDateChooser txt_fecharetiro;
    public javax.swing.JTextField txt_idremitente;
    public javax.swing.JComboBox<String> txt_paquete_Tipoentrega;
    public javax.swing.JComboBox<String> txt_paquete_electronico;
    public javax.swing.JComboBox<String> txt_paquete_fragil;
    public javax.swing.JTextField txt_peso;
    public javax.swing.JComboBox<String> txt_revista_catalogo;
    public javax.swing.JTextField txt_revista_nombre;
    public javax.swing.JComboBox<String> txt_revista_tema;
    public javax.swing.JComboBox<String> txt_tipoarticulo;
    public javax.swing.JComboBox<String> txt_tiposobre;
    // End of variables declaration//GEN-END:variables
}
